Repository thecartercenter/nemo, pull requests merged in 2018-10, with the labels that each got.

#503 8879: show translation
  app/assets/javascripts/views/form_items_draggable_list_view.js.coffee
Labels: ready-for-review

#509 8917 add qtypes to response feature specs
  app/models/form_item.rb
  app/models/results/web_response_parser.rb
  spec/features/results/responses/form_rendering_and_submission_spec.rb
  spec/support/contexts/response_tree.rb
Labels: ready-for-review

#496 6440 nested groups on printable form
  app/models/form.rb
  app/models/form_item.rb
  app/views/form_items/_printable.html.erb
  app/views/forms/_printable.html.erb
  spec/factories/forms.rb
  spec/models/form_spec.rb
  spec/support/contexts/odk_submissions.rb
Labels: complete

#505 8916 add reviewed column to response export
  app/models/results/csv/answer_query.rb
  app/models/results/csv/generator.rb
  config/locales/en/main.yml
  spec/fixtures/response_csv/basic.csv
  spec/fixtures/response_csv/media.csv
  spec/fixtures/response_csv/multiline.csv
  spec/fixtures/response_csv/multilingual.csv
  spec/fixtures/response_csv/scoped_relation.csv
  spec/fixtures/response_csv/with_deleted.csv
  spec/fixtures/response_csv/with_repeat_groups.csv
  spec/models/results/csv/generator_spec.rb
  spec/requests/responses_csv_spec.rb
Labels: complete

#510 8102 operations migration
  app/controllers/option_set_imports_controller.rb
  app/controllers/user_batches_controller.rb
  app/helpers/operations_helper.rb
  app/models/mission.rb
  app/models/operation.rb
  app/views/operations/show.html.erb
  config/locales/en/main.yml
  db/migrate/20181004181337_refactor_operations_to_have_mission_and_new_attributes.rb
  db/schema.rb
  spec/factories/operations.rb
Labels: complete

#511 6676 csv export background job
  app/controllers/concerns/application_controller/error_handling.rb
  app/controllers/operations_controller.rb
  app/controllers/option_set_imports_controller.rb
  app/controllers/responses_controller.rb
  app/controllers/user_batches_controller.rb
  app/helpers/elmo_form_builder.rb
  app/helpers/operations_helper.rb
  app/jobs/operation_job.rb
  app/jobs/response_csv_export_operation_job.rb
  app/jobs/tabular_import_operation_job.rb
  app/models/operation.rb
  app/models/results/csv/generator.rb
  app/views/operations/show.html.erb
  config/locales/en/main.yml
  config/routes.rb
  db/migrate/20181004141846_remove_job_outcome_url.rb
  db/migrate/20181004142157_add_attachment_to_operations.rb
  db/migrate/20181004155009_add_attachment_download_name_to_operations.rb
  db/migrate/20181010174613_add_url_to_operations.rb
  db/schema.rb
  spec/factories/operations.rb
  spec/features/results/responses/csv_export_spec.rb
  spec/jobs/operation_job_spec.rb
  spec/models/results/csv/generator_spec.rb
  spec/requests/responses_csv_spec.rb
Labels: needs-minor-revision

#516 8930 add operations panel link permanently on navbar
  app/helpers/operations_helper.rb
  config/locales/en/main.yml
Labels: complete

#517 8954 odk 422 error
  app/controllers/media/objects_controller.rb
  app/models/media/audio.rb
  app/models/media/image.rb
  app/models/media/object.rb
  app/models/media/video.rb
  app/models/odk/answer_parser.rb
  config/initializers/paperclip.rb
  spec/factories/media_objects.rb
  spec/fixtures/media/images/not_an_image.ogg
  spec/fixtures/odk/responses/simple_response.xml
  spec/models/media/audio_spec.rb
  spec/models/media/image_spec.rb
  spec/models/media/object_spec.rb
  spec/models/media/video_spec.rb
  spec/models/odk/response_parser_spec.rb
  spec/requests/media/objects_spec.rb
  spec/support/contexts/media.rb
Labels: complete

#522 8979 generalize media uploader
  app/assets/javascripts/views/file_uploader_view.js.coffee
  app/assets/javascripts/views/media_uploader_manager.js.coffee
  app/assets/javascripts/views/media_uploader_view.js.coffee
  app/views/layouts/_dropzone_preview.html.erb
  app/views/responses/answers/_media_editable.html.erb
  app/views/responses/form.html.erb
  config/i18n-js.yml
  config/locales/en/main.yml
  spec/support/contexts/dropzone.rb
Labels: complete

#513 8927 operations shows error when delayed job stopped
  app/controllers/operations_controller.rb
  app/controllers/ping_controller.rb
  app/jobs/operation_job.rb
  app/models/delayed_job_checker.rb
  config/locales/en/main.yml
  spec/features/operations/operations_panel_spec.rb
Labels: complete

#524 8995: Fix DelayedJobChecker to check DB
  app/controllers/operations_controller.rb
  app/controllers/ping_controller.rb
  app/models/delayed_job_checker.rb
  app/models/util/delayed_job_checker.rb
  app/views/ping/show.text.erb
  spec/features/operations/operations_panel_spec.rb
  spec/models/util/delayed_job_checker_spec.rb
Labels: complete

#521 8946 background sms broadcasts
  app/controllers/application_controller.rb
  app/controllers/broadcasts_controller.rb
  app/controllers/concerns/application_controller/settings.rb
  app/controllers/concerns/operation_queueable.rb
  app/controllers/option_set_imports_controller.rb
  app/controllers/responses_controller.rb
  app/controllers/sms_controller.rb
  app/controllers/user_batches_controller.rb
  app/helpers/broadcasts_helper.rb
  app/helpers/operations_helper.rb
  app/jobs/broadcast_operation_job.rb
  app/jobs/operation_job.rb
  app/jobs/response_csv_export_operation_job.rb
  app/jobs/tabular_import_operation_job.rb
  app/models/broadcast.rb
  app/models/operation.rb
  app/models/option_set_import.rb
  app/models/sms/adapters/adapter.rb
  app/models/sms/adapters/fatal_send_error.rb
  app/models/sms/adapters/partial_send_error.rb
  app/models/sms/adapters/twilio_adapter.rb
  app/models/sms/broadcaster.rb
  app/models/sms/decoder/decoding_error.rb
  app/models/sms/decoder/parse_error.rb
  app/models/sms/error.rb
  app/models/sms/generic_error.rb
  app/models/sms/unverified_token_error.rb
  app/models/user_batch.rb
  app/views/operations/show.html.erb
  config/locales/en/main.yml
  config/locales/en/operation.yml
  config/routes.rb
  db/migrate/20181015154427_add_sent_at_to_broadcasts.rb
  db/schema.rb
  docs/erd.pdf
  spec/features/broadcasts_flow_spec.rb
  spec/features/results/responses/csv_export_spec.rb
  spec/features/results/responses/location_picker_spec.rb
  spec/jobs/broadcast_operation_job_spec.rb
  spec/models/sms/adapters/sms_adapter_spec.rb
  spec/requests/broadcasts_controller_spec.rb
  spec/requests/sms/incoming_sms_spec.rb
Labels: in progress

#508 7479 option set clone
  app/models/ability.rb
  app/models/form.rb
  app/models/option_node.rb
  app/models/option_set.rb
  app/models/question.rb
  app/models/replication/obj_proxy.rb
  app/models/replication/replicable.rb
  app/views/forms/_screen.html.erb
  app/views/option_sets/_form.html.erb
  docs/answer_assertions.sql
  docs/option_set_assertions.sql
  docs/production-setup.md
  lib/task_helpers/option_set_reclone.rb
  lib/tasks/option_set_reclone.rake
  spec/models/form_spec.rb
  spec/models/mission_destroy_spec.rb
  spec/models/replication/form_replication_spec.rb
  spec/models/replication/option_set_replication_spec.rb
  spec/models/replication/question_replication_spec.rb
  spec/models/report/list_report_spec.rb
  spec/task_helpers/option_set_reclone_spec.rb
Labels: in progress
